#!/usr/bin/env Rscript

###### 
# This script will generate general covariate information tables about the DEP samples:
# usage: ./DEP_sample_info_covariates_110314ERD.R
# input: 	original table
#			covariate table
# output: 	4 tables of the number of samples by class~phase, 4ish included and not 
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################




##### Function to generate summary table:
MakeATable <- function(d) {
	n <- dim(d)[1]
	n_phase <- table(d$Phase)
	cohort_phase <- table(d$Cohort, d$Phase)
	rownames(cohort_phase) <- paste0("cohort_", rownames(cohort_phase))
	mm_phase <- table(d$Mastermix, d$Phase)
	rank_phase <- table(d$Rank, d$Phase)
	rownames(rank_phase) <- paste0("rank_", rownames(rank_phase))
	
	metable <- rbind(n_phase, cohort_phase, mm_phase, rank_phase)
	metable <- cbind(rowSums(metable), metable)
	colnames(metable)[1] <- "n"
	return(metable)
}



##### Run on before and after taking two samples out, with phase_4 and without:
# Original, with 4ish separate:
orig <- read.table(file="../results/1_general/Monkey_poop_log_parsed_seq_ids_011714ERD.txt", sep="\t", header=TRUE)
orit.table <- MakeATable(orig)
write.table(orit.table, paste0("../results/1_general/summary_table_all_samples_4ish_covs_",today,"ERD.txt"), sep="\t", quote=FALSE)

# Original, with 4ish included:
orig$Phase[grep("4ish", orig$Phase)] <- "phase_4"
orig.table <- MakeATable(orig)
write.table(orig.table, paste0("../results/1_general/summary_table_all_samples_4ish_incl_covs_",today,"ERD.txt"), sep="\t", quote=FALSE)

# -2, with 4ish separate:
new <- read.table(file="../results/3_data/table_covariates_DEP_103114ERD.txt", sep="\t", header=TRUE)
new.table <- MakeATable(new)
write.table(new.table, paste0("../results/2_general_sub/summary_table_sub_4ish_covs_",today,"ERD.txt"), sep="\t", quote=FALSE)

# -1, with 4ish included:
new$Phase[grep("4ish", new$Phase)] <- "phase_4"
newt.table <- MakeATable(new)
write.table(newt.table, paste0("../results/2_general_sub/summary_table_sub_4ish_incl_covs_",today,"ERD.txt"), sep="\t", quote=FALSE)

print("DONE!")


	
	