# 5/29/14

#!/usr/bin/env Rscript

###### 
# This script will generate a plot of the reads classified to each taxonomic level for each sample
# input: 	tables of reads classified to each taxonomic level
#			table of reads per sample after read QC
# output: 	plot of reads classified to each level for each sample
# 			table of summary statistics for each step
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
input.path <- c("../data/FC1/summaries/")	# path for all output to go into
#############################


##### Number of reads after read QC:
seqed <- read.table(file=paste(input.path, "reads_sequenced_per_sample_061014ERD.txt", sep=""), sep="\t", header=FALSE)
qced <- read.table(file=paste(input.path, "reads_after_read_QC_061014ERD.txt", sep=""), sep="\t", header=FALSE)
phylum <- read.table(file=paste(input.path, "DEP.FC1.phylum.reads.061014ERD.txt", sep=""), header=TRUE, sep="\t")
class <- read.table(file=paste(input.path, "DEP.FC1.class.reads.061014ERD.txt", sep=""), header=TRUE, sep="\t")
order <- read.table(file=paste(input.path, "DEP.FC1.order.reads.061014ERD.txt", sep=""), header=TRUE, sep="\t")
family <- read.table(file=paste(input.path, "DEP.FC1.family.reads.061014ERD.txt", sep=""), header=TRUE, sep="\t")
genus <- read.table(file=paste(input.path, "DEP.FC1.genus.reads.061014ERD.txt", sep=""), header=TRUE, sep="\t")

merged <- merge(qced, phylum, by.x="V2", by.y="read.tots", all=TRUE)
colnames(merged)[1] <- "read.tots"
merged <- merge(merged, class, by="read.tots", all=TRUE)
merged <- merge(merged, order, by="read.tots", all=TRUE)
merged <- merge(merged, family, by="read.tots", all=TRUE)
merged <- merge(merged, genus, by="read.tots", all=TRUE)

colnames(merged) <- c("sample", "reads", "phylum", "class", "order", "family", "genus")
write.table(merged, paste("../results/1_general/table_reads_classified_each_level_",today,"ERD.txt", sep=""), sep="\t", quote=FALSE, row.names=FALSE)




##### Plot reads classified at each level:
sorted <- merged[order(as.numeric(as.character(merged$reads))),]

pdf(paste("../results/1_general/plot_reads_classified_each_level_",today,"ERD.pdf", sep=""))
barplot(sorted$reads, col="gray", main="DEP: reads classified to each taxonomic level", xlab="samples", ylab="reads")
barplot(sorted$phylum, col="red", add=TRUE)
barplot(sorted$class, col="orange", add=TRUE)
barplot(sorted$order, col="yellow", add=TRUE)
barplot(sorted$family, col="green", add=TRUE)
barplot(sorted$genus, col="blue", add=TRUE)
legend("topleft", legend=colnames(sorted[2:dim(sorted)[2]]), fill=c("gray", "red", "orange", "yellow", "green", "blue"))
dev.off() 


##### Generate a table of summary statistics:
summaries <- summary(seqed$V2)
summaries <- rbind(summaries, summary(qced$V1))
summaries <- rbind(summaries, summary(sorted$phylum))
summaries <- rbind(summaries, summary(sorted$class))
summaries <- rbind(summaries, summary(sorted$order))
summaries <- rbind(summaries, summary(sorted$family))
summaries <- rbind(summaries, summary(sorted$genus))
rownames(summaries) <- c("sequenced", "after_qc", "phylum", "class", "order", "family", "genus")

write.table(summaries, paste("../results/1_general/table_reads_at_each_step_and_level_summary_",today,"ERD.txt", sep=""), quote=FALSE)


print("DONE!")
