#!/usr/bin/env Rscript

###### 
# This script will generate a plot of the reads classified to each taxonomic level for each sample
# after subsampling for the DEP project (FC3)
# usage: ./FC3_summary_statistics_each_step_subsampled_102914ERD.R
# input: 	tables of reads classified to each taxonomic level
#			table of reads per sample after read QC
# output: 	plot of reads classified to each level for each sample
# 			table of summary statistics for each step
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
input.path <- c("../data/FC3/summary_files/")	# path for all output to go into
#############################


##### Number of reads after read QC:
seqed <- read.table(file=paste(input.path, "reads_sequenced_per_sample_091114ERD.txt", sep=""), sep="\t", header=FALSE)
qced <- read.table(file=paste(input.path, "reads_after_read_QC_091114ERD.txt", sep=""), sep="\t", header=FALSE)
phylum <- read.table(file=paste(input.path, "DEP.FC3.sub.phylum.reads.102914ERD.txt", sep=""), header=TRUE, sep="\t")
class <- read.table(file=paste(input.path, "DEP.FC3.sub.class.reads.102914ERD.txt", sep=""), header=TRUE, sep="\t")
order <- read.table(file=paste(input.path, "DEP.FC3.sub.order.reads.102914ERD.txt", sep=""), header=TRUE, sep="\t")
family <- read.table(file=paste(input.path, "DEP.FC3.sub.family.reads.102914ERD.txt", sep=""), header=TRUE, sep="\t")
genus <- read.table(file=paste(input.path, "DEP.FC3.sub.genus.reads.102914ERD.txt", sep=""), header=TRUE, sep="\t")

merged <- merge(seqed, qced, by.x="V1", by.y="V2")
colnames(merged)[1] <- "read.tots"
merged <- merge(merged, phylum, by="read.tots")
merged <- merge(merged, class, by="read.tots")
merged <- merge(merged, order, by="read.tots")
merged <- merge(merged, family, by="read.tots")
merged <- merge(merged, genus, by="read.tots")

colnames(merged) <- c("sample", "total_reads", "qc_reads", "phylum", "class", "order", "family", "genus")
write.table(merged, paste("../results/2_general_sub/table_reads_classified_each_level_subsampled_",today,"ERD.txt", sep=""), sep="\t", quote=FALSE, row.names=FALSE)




##### Plot reads classified at each level:
sorted <- merged[order(as.numeric(as.character(merged$total_reads))),]

pdf(paste("../results/2_general_sub/plot_reads_classified_each_level_FC3_",today,"ERD.pdf", sep=""))
barplot(sorted$total_reads, col="black", main="DEP: reads classified to each taxonomic level", xlab="samples", ylab="reads")
barplot(sorted$qc_reads, col="gray", add=TRUE)
barplot(sorted$phylum, col="red", add=TRUE)
barplot(sorted$class, col="orange", add=TRUE)
barplot(sorted$order, col="yellow", add=TRUE)
barplot(sorted$family, col="green", add=TRUE)
barplot(sorted$genus, col="blue", add=TRUE)
legend("topleft", legend=paste(colnames(sorted[2:dim(sorted)[2]]), " (median = ", apply(sorted[,2:dim(sorted)[2]], 2, median), ")", sep=""), fill=c("black", "gray", "red", "orange", "yellow", "green", "blue"))
abline(h=median(sorted$total_reads), col="black")
abline(h=median(sorted$qc_reads), col="gray")
abline(h=median(sorted$phylum), col="red")
abline(h=median(sorted$class), col="orange")
abline(h=median(sorted$order), col="yellow")
abline(h=median(sorted$family), col="green")
abline(h=median(sorted$genus), col="blue")
dev.off() 

# That, but without the total and QC reads:
sorted <- merged[order(as.numeric(as.character(merged$phylum))),]

pdf(paste("../results/2_general_sub/plot_reads_classified_each_level_FC3_taxa_only_",today,"ERD.pdf", sep=""))
barplot(sorted$phylum, col="red", main="DEP: reads classified to each taxonomic level", xlab="samples", ylab="reads")
barplot(sorted$class, col="orange", add=TRUE)
barplot(sorted$order, col="yellow", add=TRUE)
barplot(sorted$family, col="green", add=TRUE)
barplot(sorted$genus, col="blue", add=TRUE)
legend("bottomright", legend=paste(colnames(sorted[2:dim(sorted)[2]]), " (median = ", apply(sorted[,2:dim(sorted)[2]], 2, median), ")", sep=""), fill=c("black", "gray", "red", "orange", "yellow", "green", "blue"), bg="white")
abline(h=median(sorted$phylum), col="red")
abline(h=median(sorted$class), col="orange")
abline(h=median(sorted$order), col="yellow")
abline(h=median(sorted$family), col="green")
abline(h=median(sorted$genus), col="blue")
dev.off() 



##### Generate a table of summary statistics:
summaries <- summary(sorted$total_reads)
summaries <- rbind(summaries, summary(sorted$qc_reads))
summaries <- rbind(summaries, summary(sorted$phylum))
summaries <- rbind(summaries, summary(sorted$class))
summaries <- rbind(summaries, summary(sorted$order))
summaries <- rbind(summaries, summary(sorted$family))
summaries <- rbind(summaries, summary(sorted$genus))
summaries <- cbind(summaries, c(NA, NA, summaries[3:dim(summaries)[1],3]/500000))
rownames(summaries) <- c("sequenced", "after_qc", "phylum", "class", "order", "family", "genus")
colnames(summaries)[7] <- "perc_remaining"

write.table(summaries, paste("../results/2_general_sub/table_reads_at_each_step_and_level_summary_FC3_",today,"ERD.txt", sep=""), quote=FALSE)



##### Barplot by phase:
phase_cols <- function(sname) {
	if (grepl("phase1", sname)) {
		return("gold")
	} else if (grepl("phase2", sname)) {
		return("hotpink1")
	} else if (grepl("phase3", sname)) {
		return("chocolate4")
	} else if (grepl("phase4", sname)) {
		return("blue")
	}
}

phases <- c("phase1", "phase2", "phase3", "phase4")

for (i in 4:8) { 
	lev <- colnames(sorted)[i]
	pdf(paste("../results/2_general_sub/plot_by_phase_",lev,"_",today,"ERD.pdf", sep=""))
	barplot(sorted[,i], col=sapply(sorted$sample, phase_cols), ylim=c(0,500000), main=paste0("DEP: reads by phase - ",lev), xlab="samples", ylab="reads")
	for (j in phases) {
		abline(h=median(sorted[grep(j, sorted$sample),i]), col=sapply(j, phase_cols))
	}
	legend("bottomright", legend=phases, fill=sapply(phases, phase_cols), bg="white")
	dev.off()
}

print("DONE!")
