#!/usr/bin/env Rscript

###### 
# This script will generate a plot of the reads classified to each taxonomic level for each sample
# With and without the Hutterite reads for flowcell 3 for DEP project.
# input: 	tables of reads classified to each taxonomic level
#			table of reads per sample after read QC
# output: 	plot of reads classified to each level for each sample
# 			table of summary statistics for each step
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
input.path <- c("../data/FC3/summary_files/")	# path for all output to go into
#############################


##### Number of reads after read QC:
seqed <- read.table(file=paste(input.path, "reads_sequenced_per_sample_091114ERD.txt", sep=""), sep="\t", header=FALSE)
qced <- read.table(file=paste(input.path, "reads_after_read_QC_091114ERD.txt", sep=""), sep="\t", header=FALSE)
phylum <- read.table(file=paste(input.path, "DEP.FC3.phylum.reads.091514ERD.txt", sep=""), header=TRUE, sep="\t")
class <- read.table(file=paste(input.path, "DEP.FC3.class.reads.091514ERD.txt", sep=""), header=TRUE, sep="\t")
order <- read.table(file=paste(input.path, "DEP.FC3.order.reads.091514ERD.txt", sep=""), header=TRUE, sep="\t")
family <- read.table(file=paste(input.path, "DEP.FC3.family.reads.091514ERD.txt", sep=""), header=TRUE, sep="\t")
genus <- read.table(file=paste(input.path, "DEP.FC3.genus.reads.091514ERD.txt", sep=""), header=TRUE, sep="\t")

merged <- merge(seqed, qced, by.x="V1", by.y="V2")
colnames(merged)[1] <- "read.tots"
merged <- merge(merged, phylum, by="read.tots", all=TRUE)
merged <- merge(merged, class, by="read.tots", all=TRUE)
merged <- merge(merged, order, by="read.tots", all=TRUE)
merged <- merge(merged, family, by="read.tots", all=TRUE)
merged <- merge(merged, genus, by="read.tots", all=TRUE)

colnames(merged) <- c("sample", "total_reads", "qc_reads", "phylum", "class", "order", "family", "genus")
write.table(merged, paste("../results/1_general/table_reads_classified_each_level_FC3_with_Hutts_",today,"ERD.txt", sep=""), sep="\t", quote=FALSE, row.names=FALSE)




##### Plot reads classified at each level:
sorted <- merged[order(as.numeric(as.character(merged$total_reads))),]

pdf(paste("../results/1_general/plot_reads_classified_each_level_FC3_with_Hutts_",today,"ERD.pdf", sep=""))
barplot(sorted$total_reads, col="black", main="DEP: reads classified to each taxonomic level", xlab="samples", ylab="reads")
barplot(sorted$qc_reads, col="gray", add=TRUE)
barplot(sorted$phylum, col="red", add=TRUE)
barplot(sorted$class, col="orange", add=TRUE)
barplot(sorted$order, col="yellow", add=TRUE)
barplot(sorted$family, col="green", add=TRUE)
barplot(sorted$genus, col="blue", add=TRUE)
legend("topleft", legend=paste(colnames(sorted[2:dim(sorted)[2]]), " (median = ", apply(sorted[,2:dim(sorted)[2]], 2, median), ")", sep=""), fill=c("black", "gray", "red", "orange", "yellow", "green", "blue"))
abline(h=median(sorted$total_reads), col="black")
abline(h=median(sorted$qc_reads), col="gray")
abline(h=median(sorted$phylum), col="red")
abline(h=median(sorted$class), col="orange")
abline(h=median(sorted$order), col="yellow")
abline(h=median(sorted$family), col="green")
abline(h=median(sorted$family), col="blue")
dev.off() 




##### Divide into Hutterite and DEP:
# DEP:

merged2 <- merged[-grep("HUTT", merged$sample),]
sorted <- merged2[order(as.numeric(as.character(merged2$total_reads))),]

pdf(paste("../results/1_general/plot_reads_classified_each_level_FC3_",today,"ERD.pdf", sep=""))
barplot(sorted$total_reads, col="black", main="DEP: reads classified to each taxonomic level", xlab="samples", ylab="reads")
barplot(sorted$qc_reads, col="gray", add=TRUE)
barplot(sorted$phylum, col="red", add=TRUE)
barplot(sorted$class, col="orange", add=TRUE)
barplot(sorted$order, col="yellow", add=TRUE)
barplot(sorted$family, col="green", add=TRUE)
barplot(sorted$genus, col="blue", add=TRUE)
legend("topleft", legend=paste(colnames(sorted[2:dim(sorted)[2]]), " (median = ", apply(sorted[,2:dim(sorted)[2]], 2, median), ")", sep=""), fill=c("black", "gray", "red", "orange", "yellow", "green", "blue"))
abline(h=median(sorted$total_reads), col="black")
abline(h=median(sorted$qc_reads), col="gray")
abline(h=median(sorted$phylum), col="red")
abline(h=median(sorted$class), col="orange")
abline(h=median(sorted$order), col="yellow")
abline(h=median(sorted$family), col="green")
abline(h=median(sorted$family), col="blue")
dev.off() 


##### Generate a table of summary statistics:
summaries <- summary(sorted$total_reads)
summaries <- rbind(summaries, summary(sorted$qc_reads))
summaries <- rbind(summaries, summary(sorted$phylum))
summaries <- rbind(summaries, summary(sorted$class))
summaries <- rbind(summaries, summary(sorted$order))
summaries <- rbind(summaries, summary(sorted$family))
summaries <- rbind(summaries, summary(sorted$genus))
summaries <- cbind(summaries, c(NA, NA, summaries[3:dim(summaries)[1],3]/summaries[2,3]))
rownames(summaries) <- c("sequenced", "after_qc", "phylum", "class", "order", "family", "genus")
colnames(summaries)[7] <- "perc_remaining"

write.table(summaries, paste("../results/1_general/table_reads_at_each_step_and_level_summary_FC3_",today,"ERD.txt", sep=""), quote=FALSE)


# Hutts:
merged3 <- merged[grep("HUTT", merged$sample),]
sorted <- merged3[order(as.numeric(as.character(merged3$total_reads))),]

pdf(paste("../results/1_general/plot_reads_classified_each_level_FC3_Hutts_only_",today,"ERD.pdf", sep=""))
barplot(sorted$total_reads, col="black", main="DEP: reads classified to each taxonomic level", xlab="samples", ylab="reads")
barplot(sorted$qc_reads, col="gray", add=TRUE)
barplot(sorted$phylum, col="red", add=TRUE)
barplot(sorted$class, col="orange", add=TRUE)
barplot(sorted$order, col="yellow", add=TRUE)
barplot(sorted$family, col="green", add=TRUE)
barplot(sorted$genus, col="blue", add=TRUE)
legend("topleft", legend=paste(colnames(sorted[2:dim(sorted)[2]]), " (median = ", apply(sorted[,2:dim(sorted)[2]], 2, median), ")", sep=""), fill=c("black", "gray", "red", "orange", "yellow", "green", "blue"))
abline(h=median(sorted$total_reads), col="black")
abline(h=median(sorted$qc_reads), col="gray")
abline(h=median(sorted$phylum), col="red")
abline(h=median(sorted$class), col="orange")
abline(h=median(sorted$order), col="yellow")
abline(h=median(sorted$family), col="green")
abline(h=median(sorted$family), col="blue")
dev.off() 



print("DONE!")
