#!/usr/bin/env Rscript

###### 
# This script will generate data files that are standardized by total number of reads 
# usage: ./generate_standardized_data_tables_103014ERD.R
# input: 	tables of reads classified to each taxonomic level
#			table of reads per sample after read QC
# output: 	standardized abundance tables
#			table of reads after QC subsampling
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
input.path <- c("../data/FC3/summary_files/")	# path for all output to go into
#############################



##### Read in table of reads per sample:
reads <- read.table(file="../results/2_general_sub/table_reads_classified_each_level_subsampled_103014ERD.txt", sep="\t", header=TRUE)
sub_me <- function(x) {
	if (x < 500000) {
		return(x) 
	} else {
		return(500000)
	}
}

sub <- sapply(reads$qc_reads, sub_me)



##### Read in each level and standardize:
for (a in c("phylum", "class", "order", "family", "genus")) {
	taxa <- read.table(file=paste0(input.path, "DEP.FC3.sub.",a,".counts.102914ERD.txt"), sep="\t", header=TRUE)
	rownames(taxa) <- taxa$Fam
	taxa <- taxa[,-1]
	
	taxa2 <- taxa
	for (i in 1:dim(taxa2)[2]) {
		taxa2[,i] <- taxa2[,i]/sub[i]
	}
	
	write.table(taxa2, paste0("../results/3_data/table_DEP_standardized_abundances_",a,"_",today,"ERD.txt"), sep="\t", quote=FALSE)
}



##### Write table of standardized reads:
newsub <- cbind(as.character(reads$sample), sub)
colnames(newsub) <- c("sample", "reads")
write.table(newsub, paste0("../results/2_general_sub/table_reads_subsampled_DEP_",today,"ERD.txt"), sep="\t", row.names=FALSE, quote=FALSE)

	
print("DONE!")