#!/usr/bin/env Rscript

###### 
# This script will generate a table of covariates in the same order as individuals in the taxa tables
# usage: ./generate_covariate_table_subs_103014ERD.R
# input: 	abundance table
#			table of possible confounders
# output: 	table of covariates in the same order as data tables
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
input.path <- c("../results/3_data/")	
#############################



##### Read in table of possible counfounders:
covs <- read.table(file="../results/1_general/Monkey_poop_log_parsed_seq_ids_011714ERD.txt", sep="\t", header=TRUE)



##### Generate covariate table:
a <- "phylum"
taxa <- read.table(file=paste0(input.path, "table_DEP_standardized_abundances_",a,"_103014ERD.txt"), sep="\t", header=TRUE)

samples <- colnames(taxa)

samps <- c()
for (i in 1:length(samples)) {
	samps <- rbind(samps, strsplit(samples[i], split="_")[[1]][2:3])
}

samps[,2] <- gsub("phase", "phase_", samps[,2])

ind <- c()
for (i in 1:dim(samps)[1]) {
	ind <- c(ind, which(covs$Animal == samps[i,1] & covs$Phase == samps[i,2]))
}

mycovs <- covs[ind,]

mycovs <- cbind(samples, mycovs)
mycovs$Run[which(mycovs$Run == "M602/604")] <- "M603/604"

write.table(mycovs, paste0(input.path, "table_covariates_DEP_",today,"ERD.txt"), sep="\t", row.names=FALSE, quote=FALSE)

print("DONE!")




