#!/usr/bin/env Rscript

###### 
# This script will generate a table of diversity metrics for the DEP fecal samples.
# usage: ./generate_diversity_metrics_110514ERD.R
# input: 	abundance tables
# output: 	table of diversity metrics 
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### Load library:
suppressMessages(library("vegan"))



##### Read in genus level data and calculate diversity metrics:
taxa <- read.table(file="../results/3_data/table_DEP_standardized_abundances_genus_103014ERD.txt", sep="\t", header=TRUE)

S <- specnumber(t(taxa))
H <- diversity(t(taxa), index="shannon")
J <- H/log(S)

diverse <- rbind(S, H, J)

write.table(diverse, paste0("../results/13_diversity/diversity_metrics_DEP_",today,"ERD.txt"), sep="\t", quote=FALSE)

print("DONE!")
