#!/usr/bin/env Rscript

###### 
# This script will do a lmm for the DEP samples, with rank as a fixed effect and animal, run, and phase as random effects
# usage: ./lmm_DEP_all_taxa_103114ERD.R
# input: 	abundance tables
#			table of possible confounders
# output: 	table of pvalues and qvalues for associations
#			histogram of p-values
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
input.path <- c("../results/3_data/")	
#############################



##### Load libraries:
library("lme4")
library("qvalue")



##### Read in table of covariates:
covs <- read.table(file=paste0(input.path, "table_covariates_DEP_103114ERD.txt"), sep="\t", header=TRUE)
# Change phase 4ish to phase 4:
covs$Phase[grep("4ish", covs$Phase)] <- "phase_4"



##### Do models for rank for each bacteria:
assocs <- c()
for (a in c("phylum", "class", "order", "family", "genus")) {
	print(a)
	taxa <- read.table(file=paste0(input.path, "table_DEP_standardized_abundances_",a,"_103014ERD.txt"), sep="\t", header=TRUE)
	
	for (i in 1:dim(taxa)[1]) {
		# If the bacteria isn't in more than 1 person, skip to next:
		if (length(which(taxa[i,] != 0)) < 2) {
			next
		}
		bacteria <- rownames(taxa)[i]
		nullmodel <- lmer(as.numeric(taxa[i,]) ~(1|as.factor(covs$Animal)) + (1|as.factor(covs$Phase)) + (1|as.factor(covs$Run)), REML=FALSE)
		mymodel <- lmer(as.numeric(taxa[i,]) ~ as.numeric(covs$Rank) + (1|as.factor(covs$Animal)) + (1|as.factor(covs$Phase)) + (1|as.factor(covs$Run)), REML=FALSE)
		mylrt <- anova(nullmodel,mymodel)
		mylrtp <- mylrt$"Pr(>Chisq)"[2]
		assocs <- rbind(assocs, c(bacteria, mylrtp))
	}
}

qvalues <- qvalue(as.numeric(assocs[,2]))$qvalue
assocs <- cbind(assocs, qvalues)
colnames(assocs) <- c("bacteria", "pvalue", "qvalue")
write.table(assocs, paste0("../results/5_lmm/table_p_and_q_values_lmm_",today,"ERD.txt"), sep="\t", row.names=FALSE, quote=FALSE)


pdf(paste0("../results/5_lmm/hist_lmm_pvalues_",today,"ERD.pdf"))
hist(as.numeric(assocs[,2]), col="gray", main="LMM pvalues")
dev.off()

print("DONE!")