#!/usr/bin/env Rscript

###### 
# This script will do a lmm for diversity of the DEP samples, with rank as a fixed effect and animal, run, and phase as random effects. Mastermix and date collected are regressed out first.
# usage: ./lmm_DEP_diversity_all_taxa_covs_regressed_110514ERD.R
# input: 	diversity table
#			table of possible confounders
# output: 	table of pvalues and qvalues for associations
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### Load libraries:
suppressWarnings(suppressMessages(library("lme4")))
suppressWarnings(suppressMessages(library("qvalue")))
options(warn=2)



##### Read in table of covariates:
covs <- read.table(file="../results/3_data/table_covariates_DEP_103114ERD.txt", sep="\t", header=TRUE)
# Change phase 4ish to phase 4:
covs$Phase[grep("4ish", covs$Phase)] <- "phase_4"



##### Do models for rank for each bacteria:
taxa <- read.table(file="../results/13_diversity/diversity_metrics_DEP_110514ERD.txt", sep="\t", header=TRUE)

assocs <- c()
for (i in 1:dim(taxa)[1]) {
	# Regress out mastermix and date collected:		
	mylm <- lm(as.numeric(taxa[i,]) ~ as.factor(covs$Mastermix) + as.factor(covs$Date_Collected), na.action=na.exclude)
	resids <- resid(mylm)	
	
	# Do LMM:
	bacteria <- rownames(taxa)[i]
	mytry <- try(nullmodel <- lmer(as.numeric(resids) ~ (1|as.factor(covs$Animal)) + (1|as.factor(covs$Phase)) + (1|as.factor(covs$Run)), REML=FALSE), silent=TRUE)
	mytry2 <- try(mymodel <- lmer(as.numeric(resids) ~ as.numeric(covs$Rank) + (1|as.factor(covs$Animal)) + (1|as.factor(covs$Phase)) + (1|as.factor(covs$Run)), REML=FALSE), silent=TRUE)
	mytry3 <- try(mylrt <- anova(nullmodel, mymodel), silent=TRUE)
	if ('try-error' %in% c(class(mytry), class(mytry2), class(mytry3))) {
		next
    } else {
		mylrtp <- mylrt$"Pr(>Chisq)"[2]
		assocs <- rbind(assocs, c(bacteria, mylrtp))
	}
}

qvalues <- qvalue(as.numeric(assocs[,2]))$qvalue
assocs <- cbind(assocs, qvalues)
colnames(assocs) <- c("metric", "pvalue", "qvalue")
write.table(assocs, paste0("../results/14_lmm_diversity_covs/table_p_and_q_values_lmm_",today,"ERD.txt"), sep="\t", row.names=FALSE, quote=FALSE)

print("DONE!")