#!/usr/bin/env Rscript

###### 
# This script will do a lmm for the DEP samples to determine if there are phase effects for any of the bacteria, with phase as a fixed effect and animal, run, and rank as random effects. Mastermix and date collected are regressed out first. 
# usage: ./lmm_phase_DEP_all_taxa_covs_regressed_111214ERD.R
# input: 	abundance tables
#			table of possible confounders
# output: 	table of pvalues and qvalues for associations
#			histogram of p-values
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
input.path <- c("../results/3_data/")	
#############################



##### Load libraries:
suppressWarnings(suppressMessages(library("lme4")))
suppressWarnings(suppressMessages(library("qvalue")))
options(warn=2)



##### Read in table of covariates:
covs <- read.table(file=paste0(input.path, "table_covariates_DEP_103114ERD.txt"), sep="\t", header=TRUE)
# Change phase 4ish to phase 4:
covs$Phase[grep("4ish", covs$Phase)] <- "phase_4"



##### Do models for rank for each bacteria:
assocs <- c()
for (a in c("phylum", "class", "order", "family", "genus")) {
	print(a)
	taxa <- read.table(file=paste0(input.path, "table_DEP_standardized_abundances_",a,"_103014ERD.txt"), sep="\t", header=TRUE)
	
	for (i in 1:dim(taxa)[1]) {
		# If the bacteria isn't in more than 1 person, skip to next:
		if (length(which(taxa[i,] != 0)) < 2) {
			next
		}
		
		# Regress out mastermix and date collected:		
		mylm <- lm(as.numeric(taxa[i,]) ~ as.factor(covs$Mastermix) + as.factor(covs$Date_Collected), na.action=na.exclude)
		resids <- resid(mylm)	
	
		# Do LMM:
		bacteria <- rownames(taxa)[i]
		mytry <- try(nullmodel <- lmer(as.numeric(resids) ~ (1|as.factor(covs$Animal)) + (1|as.numeric(covs$Rank)) + (1|as.factor(covs$Run)), REML=FALSE), silent=TRUE)
		mytry2 <- try(mymodel <- lmer(as.numeric(resids) ~ as.factor(covs$Phase) + (1|as.factor(covs$Animal)) + (1|as.numeric(covs$Rank)) + (1|as.factor(covs$Run)), REML=FALSE), silent=TRUE)
		mytry3 <- try(mylrt <- anova(nullmodel, mymodel), silent=TRUE)
		if ('try-error' %in% c(class(mytry), class(mytry2), class(mytry3))) {
			next
    	} else {
			mylrtp <- mylrt$"Pr(>Chisq)"[2]
			assocs <- rbind(assocs, c(bacteria, mylrtp))
		}
	}
}

qvalues <- qvalue(as.numeric(assocs[,2]))$qvalue
assocs <- cbind(assocs, qvalues)
colnames(assocs) <- c("bacteria", "pvalue", "qvalue")
write.table(assocs, paste0("../results/16_lmm_of_phase/table_p_and_q_values_lmm_",today,"ERD.txt"), sep="\t", row.names=FALSE, quote=FALSE)



##### Summary table of number of significant hits:
qvals <- c(0.001, 0.01, 0.05, 0.10, 0.2, 1)
qval.summary <- matrix(NA, ncol=1, nrow=length(qvals))
howmany <- function(x, cutoff) {
	length(which(x <= cutoff))
}
for (i in 1:length(qvals)) {
	qval.summary[i,1] <- howmany(as.numeric(as.character(qvalues)), qvals[i])
}
rownames(qval.summary) <- qvals
colnames(qval.summary) <- c("lmm_qvalue")
write.table(qval.summary, paste0("../results/16_lmm_of_phase/table.summary.lmm.q.values.at.various.cutoffs.",today,"ERD.txt", sep=""), sep="\t", quote=FALSE)



##### Histogram and qqplot:
pdf(paste0("../results/16_lmm_of_phase/hist_qqplot_lmm_pvalues_",today,"ERD.pdf"), width=10, height=5)
par(mfrow=c(1,2))
hist(as.numeric(assocs[,2]), breaks=20, col="gray", main="LMM pvalues", xlab="p-values")

o <- -log10(sort(as.numeric(as.character(assocs[,2])), decreasing=F))
e <- -log10(1:length(o)/length(o))
plot(e,o, main=paste("qq-plot LMM", sep=""), pch=16, col=rgb(0,0,0,alpha=0.5), xlab="expected", ylab="observed")
abline(0,1, col="red")
dev.off()

print("DONE!")