#!/usr/bin/env Rscript

###### 
# This script will do a lmm for diveristy of the DEP samples, with rank as a fixed effect and run as a random effect. This is for each phase individually. Mastermix and date collected are regressed out first. 
# usage: ./lmm_DEP_diversity_each_phase_covs_regressed_110514ERD.R
# input: 	diversity tables
#			table of possible confounders
# output: 	table of pvalues and qvalues for associations
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### Load libraries:
suppressWarnings(suppressMessages(library("lme4")))
options(warn=2)


##### Read in table of covariates:
covs1 <- read.table(file="../results/3_data/table_covariates_DEP_103114ERD.txt", sep="\t", header=TRUE)
# Change phase 4ish to phase 4:
covs1$Phase[grep("4ish", covs1$Phase)] <- "phase_4"



##### Do models for rank for each bacteria, each phase:
for (p in c("phase_1", "phase_2", "phase_3", "phase_4")) {
	print(p)
	
	taxa <- read.table(file="../results/13_diversity/diversity_metrics_DEP_110514ERD.txt", sep="\t", header=TRUE)
	assocs <- c()
	
		
	# Examine only the relevant phase: 
	taxa <- taxa[,grep(p, covs1$Phase)]
	covs <- covs1[grep(p, covs1$Phase),]
	
	for (i in 1:dim(taxa)[1]) {
		# Regress out mastermix and collection date:
		mylm <- lm(as.numeric(taxa[i,]) ~ as.factor(covs$Mastermix) + as.factor(covs$Date_Collected), na.action=na.exclude)
		resids <- resid(mylm)	
		bacteria <- rownames(taxa)[i]
			
		# If there is an error in the model, null, or LRT, then just don't run it:
		mytry <- try(nullmodel <- lmer(as.numeric(resids) ~ (1|as.factor(covs$Run)), REML=FALSE), silent=TRUE)
		mytry2 <- try(mymodel <- lmer(as.numeric(resids) ~ as.numeric(covs$Rank) + (1|as.factor(covs$Run)), REML=FALSE), silent=TRUE)
		mytry3 <- try(mylrt <- anova(nullmodel,mymodel), silent=TRUE)
			
		if ('try-error' %in% c(class(mytry), class(mytry2), class(mytry3))) {
			next
   		} else {
			mylrtp <- mylrt$"Pr(>Chisq)"[2]
			assocs <- rbind(assocs, c(bacteria, p, mylrtp))
		}
	}


	corp <- p.adjust(as.numeric(assocs[,3]), method="BH")
	assocs <- cbind(assocs, corp)
	colnames(assocs) <- c("metric", "phase", "pvalue", "BH_pvalue")
	write.table(assocs, paste0("../results/15_lmm_diversity_phase_covs/table_p_and_BHpvalue_values_lmm_",p,"_",today,"ERD.txt"), sep="\t", row.names=FALSE, quote=FALSE)
}

print("DONE!")