#!/usr/bin/env Rscript

###### 
# This script will examine PCA for all levels of the DEP samples, after regressing out the covariates that were associated.
# usage: ./PCA_covariate_assoc_table_DEP_covs_regressed_111214ERD.R
# input: 	abundance tables
#			table of possible confounders
# output: 	table of covariate associations to the top 10 PCs for each taxa level
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
input.path <- c("../results/3_data/")	
#############################



##### Read in table of covariates:
covs <- read.table(file=paste0(input.path, "table_covariates_DEP_103114ERD.txt"), sep="\t", header=TRUE)
# Change phase 4ish to phase 4:
covs$Phase[grep("4ish", covs$Phase)] <- "phase_4"



##### Do PCA for each taxonomic level, regressing out animal, run, mastermix, and date collected:
for (a in c("phylum", "class", "order", "family", "genus")) {
	taxa <- read.table(file=paste0(input.path, "table_DEP_standardized_abundances_",a,"_103014ERD.txt"), sep="\t", header=TRUE)
	
	##### Regress out covariates:
	for (i in 1:dim(taxa)[1]) {
		mylm <- lm(as.numeric(taxa[i,]) ~ as.factor(covs$Run) + as.factor(covs$Mastermix) + as.factor(covs$Date_Collected), na.action=na.exclude)
		taxa[i,] <- resid(mylm)	
	}
	
	
	##### PCA:
	sum.PC <- prcomp(t(taxa), center=TRUE, scale.=FALSE)
	sumsum <- summary(sum.PC)


	##### Are the PCs associated with anything?
	cohort <- c()
	for (i in 1:10) {
		mylm <- summary(lm(sum.PC$x[,i] ~ as.factor(covs$Cohort)))
		cohort <- c(cohort, pf(mylm$fstatistic[1], mylm$fstatistic[2], mylm$fstatistic[3], lower.tail = FALSE))
	}
	
	animal <- c()
	for (i in 1:10) {
		mylm <- summary(lm(sum.PC$x[,i] ~ as.factor(covs$Animal)))
		animal <- c(animal, pf(mylm$fstatistic[1], mylm$fstatistic[2], mylm$fstatistic[3], lower.tail = FALSE))
	}
	
	run <- c()
	for (i in 1:10) {
		mylm <- summary(lm(sum.PC$x[,i] ~ as.factor(covs$Run)))
		run <- c(run, pf(mylm$fstatistic[1], mylm$fstatistic[2], mylm$fstatistic[3], lower.tail = FALSE))
	}
	
	rank <- c()
	for (i in 1:10) {
		mylm <- summary(lm(sum.PC$x[,i] ~ as.numeric(covs$Rank)))
		rank <- c(rank, pf(mylm$fstatistic[1], mylm$fstatistic[2], mylm$fstatistic[3], lower.tail = FALSE))
	}
	
	phase <- c()
	for (i in 1:10) {
		mylm <- summary(lm(sum.PC$x[,i] ~ as.factor(covs$Phase)))
		phase <- c(phase, pf(mylm$fstatistic[1], mylm$fstatistic[2], mylm$fstatistic[3], lower.tail = FALSE))
	}
	
	mm <- c()
	for (i in 1:10) {
		mylm <- summary(lm(sum.PC$x[,i] ~ as.factor(covs$Mastermix)))
		mm <- c(mm, pf(mylm$fstatistic[1], mylm$fstatistic[2], mylm$fstatistic[3], lower.tail = FALSE))
	}
	
	dc <- c()
	for (i in 1:10) {
		mylm <- summary(lm(sum.PC$x[,i] ~ as.factor(covs$Date_Collected)))
		dc <- c(dc, pf(mylm$fstatistic[1], mylm$fstatistic[2], mylm$fstatistic[3], lower.tail = FALSE))
	}	

	dr <- c()
	for (i in 1:10) {
		mylm <- summary(lm(sum.PC$x[,i] ~ as.factor(covs$Date_Rcvd)))
		dr <- c(dr, pf(mylm$fstatistic[1], mylm$fstatistic[2], mylm$fstatistic[3], lower.tail = FALSE))
	}
	
	PCApvals <- rbind(sumsum$importance[2,1:10]*100, cohort, animal, run, rank, phase, mm, dc, dr)
	rownames(PCApvals) <- c("percent_variance", "cohort", "animal", "run", "rank", "phase", "mastermix", "date_collected", "date_received")
	colnames(PCApvals) <- paste0("PC", 1:10)
	
	write.table(PCApvals, paste0("../results/4_PCA/table_PCA_pvals_",a,"_covs_regressed_",today,"ERD.txt"), sep="\t", quote=FALSE)
}
	
print("DONE!")