#!/usr/bin/env Rscript

###### 
# This script will plot PCA plots for relevant covariates
# usage: ./PCA_plots_DEP_103114booERD.R
# input: 	abundance tables
#			table of possible confounders
#			table of p-values for PCA lms
# output: 	plots for relevant confounders
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
input.path <- c("../results/3_data/")	
#############################



##### Read in table of covariates:
covs <- read.table(file=paste0(input.path, "table_covariates_DEP_103114ERD.txt"), sep="\t", header=TRUE)
# Change phase 4ish to phase 4:
covs$Phase[grep("4ish", covs$Phase)] <- "phase_4"



##### Do PCA for each taxonomic level:
for (a in c("phylum", "class", "order", "family", "genus")) {
	taxa <- read.table(file=paste0(input.path, "table_DEP_standardized_abundances_",a,"_103014ERD.txt"), sep="\t", header=TRUE)
	
	# Read in table of p-values:
	pvals <- read.table(file=paste0("../results/4_PCA/table_PCA_pvals_",a,"_103114ERD.txt"), sep="\t", header=TRUE)
	
	# If there aren't any significant associations in the top two PCs, go to next iteration of a:
	if (length(which(c(pvals$PC1, pvals$PC2) <= 0.05)) == 0) {
		print(paste0("no significant associations at ",a," level"))
		next
	}
	
	print(paste0("on ",a," level"))
	
	# PCA:
	sum.PC <- prcomp(t(taxa), center=TRUE, scale.=FALSE)
	sumsum <- summary(sum.PC)
	
	###### If either PC1 or PC2 is significant for a covariate, plot it:
	# Cohort:
	if (length(which(pvals[2,1:2] <= 0.05)) > 0) {
		# What row?
		myrow <- 2
		
		# What cov?
		mycov <- 2
		
		#PCA plot colors
		pca.point.color <- function(x) {
			if (x == 1) {
				return("gray")
			} else {
				return("black")
			}
		}
		
		# Shouldn't have to edit below here
		p1 <- pvals[myrow,1]
		p2 <- pvals[myrow,2]
		thecov <- as.factor(covs[,mycov])
		cov <- colnames(covs)[mycov]
		
		pdf(paste0("../results/4_PCA/plot_PCA_PC1_PC2_",a,"_",cov,"_",today,"ERD.pdf"))
		plot(sum.PC$x[,1],sum.PC$x[,2], col=sapply(thecov, pca.point.color), pch=16, cex=1, main=paste0("PCA - ",a," level by ",cov,"\nPC1 p = ",round(p1,4)," PC2 p = ",round(p2,4)), xlab=paste("PC 1 -", (sumsum$importance[2,1]*100),"% of variance", sep=" "),ylab=paste("PC 2 -",(sumsum$importance[2,2]*100),"% of variance",sep=" "))   
		legend("bottomleft", pch=16, legend=levels(thecov), col=sapply(levels(thecov), pca.point.color))
		dev.off()	
	}
	
	
	
	
	# Animal:
	if (length(which(pvals[3,1:2] <= 0.05)) > 0) {
		# What row?
		myrow <- 3
		
		# What cov?
		mycov <- 3
		
		
		# Shouldn't have to edit below here
		p1 <- pvals[myrow,1]
		p2 <- pvals[myrow,2]
		thecov <- as.factor(covs[,mycov])
		cov <- colnames(covs)[mycov]

		palette(terrain.colors(40))
		pdf(paste0("../results/4_PCA/plot_PCA_PC1_PC2_",a,"_",cov,"_",today,"ERD.pdf"))
		plot(sum.PC$x[,1],sum.PC$x[,2], col=thecov, pch=rep(1:10,4), cex=1, main=paste0("PCA - ",a," level by ",cov,"\nPC1 p = ",round(p1,4)," PC2 p = ",round(p2,4)), xlab=paste("PC 1 -", (sumsum$importance[2,1]*100),"% of variance", sep=" "),ylab=paste("PC 2 -",(sumsum$importance[2,2]*100),"% of variance",sep=" "))   
		legend("bottomleft", pch=rep(1:10,4), cex=0.6, legend=unique(thecov), col=1:length(thecov))
		dev.off()	
		palette("default")	
	}
	
	
	
	
	# Run:
	if (length(which(pvals[4,1:2] <= 0.05)) > 0) {
		# What row?
		myrow <- 4
		
		# What cov?
		mycov <- 4
		
		pca.point.color <- function(x) {
			if (x == "M601") {
				return("gray")
			} else if ( x == "M602") {
				return("black")
			} else if ( x == "M603/604") {
				return("red")
			} else if ( x == "M605") {
				return("blue")
			} else if ( x == "M616") {
				return("orange") 
			} else if ( x == "M617") {
				return("green") 
			} else if ( x == "M618/619") {
				return("lightblue")
			} else if ( x == "M620") {
				return("purple")
			}
		}
		
		# Shouldn't have to edit below here
		p1 <- pvals[myrow,1]
		p2 <- pvals[myrow,2]
		thecov <- as.factor(covs[,mycov])
		cov <- colnames(covs)[mycov]
		
		pdf(paste0("../results/4_PCA/plot_PCA_PC1_PC2_",a,"_",cov,"_",today,"ERD.pdf"))
		plot(sum.PC$x[,1],sum.PC$x[,2], col=sapply(thecov, pca.point.color), pch=16, cex=1, main=paste0("PCA - ",a," level by ",cov,"\nPC1 p = ",round(p1,4)," PC2 p = ",round(p2,4)), xlab=paste("PC 1 -", (sumsum$importance[2,1]*100),"% of variance", sep=" "),ylab=paste("PC 2 -",(sumsum$importance[2,2]*100),"% of variance",sep=" "))   
		legend("bottomleft", pch=16, legend=levels(thecov), col=sapply(levels(thecov), pca.point.color))
		dev.off()	
	}
	
	
	
	
	
	# Rank:
	if (length(which(pvals[5,1:2] <= 0.05)) > 0) {
		# What row?
		myrow <- 5
		
		# What cov?
		mycov <- 5
		
		pca.point.color <- function(x) {
			if (x == 1) {
				return("black")
			} else if ( x == 2) {
				return("dodgerblue4")
			} else if ( x == 3) {
				return("dodgerblue2")
			} else if ( x == 4) {
				return("cyan3")
			} else if ( x == 5) {
				return("cyan") 
			} else if ( x == 6) {
				return("gray") 
			}
		}
		
		
		# Shouldn't have to edit below here
		p1 <- pvals[myrow,1]
		p2 <- pvals[myrow,2]
		thecov <- as.factor(covs[,mycov])
		cov <- colnames(covs)[mycov]

		pdf(paste0("../results/4_PCA/plot_PCA_PC1_PC2_",a,"_",cov,"_",today,"ERD.pdf"))
		plot(sum.PC$x[,1],sum.PC$x[,2], col=sapply(thecov, pca.point.color), pch=16, cex=1, main=paste0("PCA - ",a," level by ",cov,"\nPC1 p = ",round(p1,4)," PC2 p = ",round(p2,4)), xlab=paste("PC 1 -", (sumsum$importance[2,1]*100),"% of variance", sep=" "),ylab=paste("PC 2 -",(sumsum$importance[2,2]*100),"% of variance",sep=" "))   
		legend("bottomleft", pch=16, legend=levels(thecov), col=sapply(levels(thecov), pca.point.color))
		dev.off()	
	}
	
	
	
	
	
	# Phase:
	if (length(which(pvals[6,1:2] <= 0.05)) > 0) {
		# What row?
		myrow <- 6
		
		# What cov?
		mycov <- 11
		
		pca.point.color <- function(sname) {
			if (grepl("phase_1", sname)) {
				return("gold")
			} else if (grepl("phase_2", sname)) {
				return("hotpink1")
			} else if (grepl("phase_3", sname)) {
				return("chocolate4")
			} else if (grepl("phase_4", sname)) {
				return("blue")
			}
		}
		
		
		# Shouldn't have to edit below here
		p1 <- pvals[myrow,1]
		p2 <- pvals[myrow,2]
		thecov <- as.factor(covs[,mycov])
		cov <- colnames(covs)[mycov]

		pdf(paste0("../results/4_PCA/plot_PCA_PC1_PC2_",a,"_",cov,"_",today,"ERD.pdf"))
		plot(sum.PC$x[,1],sum.PC$x[,2], col=sapply(thecov, pca.point.color), pch=16, cex=1, main=paste0("PCA - ",a," level by ",cov,"\nPC1 p = ",round(p1,4)," PC2 p = ",round(p2,4)), xlab=paste("PC 1 -", (sumsum$importance[2,1]*100),"% of variance", sep=" "),ylab=paste("PC 2 -",(sumsum$importance[2,2]*100),"% of variance",sep=" "))   
		legend("bottomleft", pch=16, legend=levels(thecov), col=sapply(levels(thecov), pca.point.color))
		dev.off()	
	}
	
	
	
	
	
	
	# Mastermix:
	if (length(which(pvals[7,1:2] <= 0.05)) > 0) {
		# What row?
		myrow <- 7
		
		# What cov?
		mycov <- 13
		
		pca.point.color <- function(x) {
			if (x == "mm1") {
				return("black")
			} else if ( x == "mm2") {
				return("gray")
			}
		}
		
		
		# Shouldn't have to edit below here
		p1 <- pvals[myrow,1]
		p2 <- pvals[myrow,2]
		thecov <- as.factor(covs[,mycov])
		cov <- colnames(covs)[mycov]

		pdf(paste0("../results/4_PCA/plot_PCA_PC1_PC2_",a,"_",cov,"_",today,"ERD.pdf"))
		plot(sum.PC$x[,1],sum.PC$x[,2], col=sapply(thecov, pca.point.color), pch=16, cex=1, main=paste0("PCA - ",a," level by ",cov,"\nPC1 p = ",round(p1,4)," PC2 p = ",round(p2,4)), xlab=paste("PC 1 -", (sumsum$importance[2,1]*100),"% of variance", sep=" "),ylab=paste("PC 2 -",(sumsum$importance[2,2]*100),"% of variance",sep=" "))   
		legend("bottomleft", pch=16, legend=levels(thecov), col=sapply(levels(thecov), pca.point.color))
		dev.off()	
	}
	
	
	
	
	# Date Collected:
	if (length(which(pvals[8,1:2] <= 0.05)) > 0) {
		# What row?
		myrow <- 8
		
		# What cov?
		mycov <- 9
		
		
		# Shouldn't have to edit below here
		p1 <- pvals[myrow,1]
		p2 <- pvals[myrow,2]
		thecov <- as.factor(covs[,mycov])
		cov <- colnames(covs)[mycov]

		palette(terrain.colors(31))
		pdf(paste0("../results/4_PCA/plot_PCA_PC1_PC2_",a,"_",cov,"_",today,"ERD.pdf"))
		plot(sum.PC$x[,1],sum.PC$x[,2], col=thecov, pch=16, cex=1, main=paste0("PCA - ",a," level by ",cov,"\nPC1 p = ",round(p1,4)," PC2 p = ",round(p2,4)), xlab=paste("PC 1 -", (sumsum$importance[2,1]*100),"% of variance", sep=" "),ylab=paste("PC 2 -",(sumsum$importance[2,2]*100),"% of variance",sep=" "))   
		legend("bottomleft", pch=16, cex=0.6, legend=unique(thecov), col=1:length(thecov))
		dev.off()	
		palette("default")	
	}





	# Date Received:
	if (length(which(pvals[9,1:2] <= 0.05)) > 0) {
		# What row?
		myrow <- 9
		
		# What cov?
		mycov <- 10
		
		pca.point.color <- function(x) {
			if (is.na(x)) {
				return("gray")
			} else if (x == "5/31/13") {
				return("black")
			} else if ( x == "6/11/13") {
				return("dodgerblue4")
			} else if ( x == "8/8/13") {
				return("dodgerblue2")
			} else if ( x == "10/28/13") {
				return("cyan3")
			} else if ( x == "10/29/13") {
				return("cyan")  
			}
		}
		
		# Shouldn't have to edit below here
		p1 <- pvals[myrow,1]
		p2 <- pvals[myrow,2]
		thecov <- as.factor(covs[,mycov])
		cov <- colnames(covs)[mycov]

		pdf(paste0("../results/4_PCA/plot_PCA_PC1_PC2_",a,"_",cov,"_",today,"ERD.pdf"))
		plot(sum.PC$x[,1],sum.PC$x[,2], col=sapply(thecov, pca.point.color), pch=16, cex=1, main=paste0("PCA - ",a," level by ",cov,"\nPC1 p = ",round(p1,4)," PC2 p = ",round(p2,4)), xlab=paste("PC 1 -", (sumsum$importance[2,1]*100),"% of variance", sep=" "),ylab=paste("PC 2 -",(sumsum$importance[2,2]*100),"% of variance",sep=" "))   
		legend("bottomleft", pch=16, legend=levels(thecov), col=sapply(levels(thecov), pca.point.color))
		dev.off()
	}
}

print("DONE!")