#!/usr/bin/env Rscript

###### 
# This script will examine PCA for all levels of the DEP samples
# usage: ./PCA_covariate_assoc_table_by_phase_DEP_103014ERD.R
# input: 	abundance tables
#			table of possible confounders
# output: 	table of covariate associations to the top 10 PCs for each taxa level
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
input.path <- c("../results/3_data/")	
#############################



##### Read in table of covariates:
thecovs <- read.table(file=paste0(input.path, "table_covariates_DEP_103114ERD.txt"), sep="\t", header=TRUE)

PCApvals <- c() 
##### Do PCA for each taxonomic level:
for (a in c("phylum", "class", "order", "family", "genus")) {
	taxa1 <- read.table(file=paste0(input.path, "table_DEP_standardized_abundances_",a,"_103014ERD.txt"), sep="\t", header=TRUE)
	
	# Separately for each phase:
	for (c in c("phase_1", "phase_2", "phase_3", "phase_4")) {
		theind <- grep(c, thecovs$Phase)
		covs <- thecovs[theind,]
		taxa <- taxa1[,theind]
	

		##### PCA:
		sum.PC <- prcomp(t(taxa), center=TRUE, scale.=FALSE)
		sumsum <- summary(sum.PC)


		##### Are the PCs associated with anything?
		rank <- c()
		for (i in 1:10) {
			mylm <- summary(lm(sum.PC$x[,i] ~ as.numeric(covs$Rank)))
			rank <- c(rank, pf(mylm$fstatistic[1], mylm$fstatistic[2], mylm$fstatistic[3], lower.tail = FALSE))
		}
	
		imp <- c(a, c, sumsum$importance[2,1:10]*100)
		ra <- c(a, c, rank)
		PCApvals <- rbind(PCApvals, imp, ra)
	}
}

colnames(PCApvals) <- c("level", "phase", paste0("PC", 1:10))
write.table(PCApvals, paste0("../results/4_PCA/table_PCA_pvals_rank_by_phase_",today,"ERD.txt"), sep="\t", quote=FALSE)
	
print("DONE!")