# 5/29/14

#!/usr/bin/env Rscript

###### 
# This script will generate a plot of the reads before and after read QC.
# input: 	table of reads per sample sequenced
#			table of reads per sample after read QC
# output: 	plot comparing reads before and after read QC
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
input.path <- c("../data/FC1/summaries/")	# path for all output to go into
#############################


##### Number of reads sequenced per sample:
lines <- read.table(file=paste(input.path, "lines_of_fastq_per_sample_052814ERD.txt", sep=""), sep="\n", header=FALSE)$V1

liners <- matrix(lines, ncol=2, byrow=TRUE)

liners[,1] <- gsub(".txt.gz", "", liners[,1])
liners[,2] <- as.numeric(liners[,2])/4
write.table(liners, paste(input.path, "reads_sequenced_per_sample_",today,"ERD.txt", sep=""), sep="\t", row.names=FALSE, col.names=FALSE, quote=FALSE)


##### Number of reads after read QC:
qced <- read.table(file=paste(input.path, "lines_of_qced_fastq_file_061014ERD.txt", sep=""), sep=" ", header=FALSE)
qced[,2] <- gsub(".txt", "", qced[,2])
qced[,1] <- qced[,1]/4
write.table(qced, paste(input.path, "reads_after_read_QC_",today,"ERD.txt", sep=""), sep="\t", row.names=FALSE, col.names=FALSE, quote=FALSE)




##### Plot reads per sample before and after read QC
merged <- merge(liners, qced, by.x="V1", by.y="V2", all=TRUE)
colnames(merged) <- c("sample", "sequenced", "qced")

s.merged <- merged[order(as.numeric(as.character(merged$sequenced))),]

pdf(paste("../results/1_general/plot.sequencing.after.read.QC.",today,"ERD.pdf", sep=""), width=10, height=5)
par(mfrow=c(1,2))
barplot(as.numeric(as.character(s.merged$sequenced)), col="gray80", main="DEP: reads sequenced/after QC", xlab="sample", ylab="reads")
barplot(as.numeric(as.character(s.merged$qced)), col="gray50", add=TRUE)
legend("topleft", fill=c("gray80", "gray50"), legend=c("reads sequenced", "reads after QC"))

barplot(log10(as.numeric(as.character(s.merged$sequenced))), col="gray80", main="DEP: reads sequenced/after QC", xlab="sample", ylab="log10(reads)")
barplot(log10(as.numeric(as.character(s.merged$qced))), col="gray50", add=TRUE)
dev.off()


print("DONE!")
