#!/usr/bin/env Rscript

###### 
# This script will plot associations for the diversity LMM, covariates regressed out, single phase, phase 4 significant associations.
# usage: ./plot_phase_4_lmm_diversity_covs_regressed_significant_associations_110514ERD.R
# input: 	diversity table
#			table of possible confounders
#			table of p and q values 
# output: 	boxplots for the significant hits
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
input.path <- c("../results/3_data/")	
#############################



##### Read in table of covariates:
covs1 <- read.table(file=paste0(input.path, "table_covariates_DEP_103114ERD.txt"), sep="\t", header=TRUE)
# Change phase 4ish to phase 4:
covs1$Phase[grep("4ish", covs1$Phase)] <- "phase_4"



##### Read in qvalue table:
qvals <- read.table(file="../results/15_lmm_diversity_phase_covs/table_p_and_BHpvalue_values_lmm_phase_4_110514ERD.txt", sep="\t", header=TRUE)



##### Read in diversity information:
alltaxa <- read.table(file="../results/13_diversity/diversity_metrics_DEP_110514ERD.txt", sep="\t", header=TRUE)
	
	
	
##### Examine only the relevant phase: 
alltaxa <- alltaxa[,grep("phase_4", covs1$Phase)]
covs <- covs1[grep("phase_4", covs1$Phase),]



##### Plot significant associations:
for (i in 1:dim(qvals)[1]) {
	if (qvals$pvalue[i] >= 0.05) {
		next
	}
	
	# get what taxa index number:
	myi <- which(rownames(alltaxa) == qvals$metric[i])

	pdf(paste0("../results/15_lmm_diversity_phase_covs/boxplot_phase4_",qvals$metric[i],"_by_rank_",today,"ERD.pdf"))
	stripchart(as.numeric(alltaxa[myi,]) ~ covs$Rank, vertical=TRUE, xlab="rank", method="jitter", ylab=qvals$metric[i], pch=16, col="gray", main=paste0(qvals$metric[i]," by rank\np-value = ",round(as.numeric(as.character(qvals$pvalue[i])), 4)," adj p-value = ",round(as.numeric(as.character(qvals$BH_pvalue[i])), 4)))
	suppressWarnings(boxplot(as.numeric(alltaxa[myi,]) ~ covs$Rank, add=TRUE, boxwex=0.35, names=rep(" ", 6), notch=TRUE, outline=FALSE)) 
	dev.off()
}

print("DONE!")
	

