#!/usr/bin/env Rscript

###### 
# This script will generate rarefaction curves for FC3 DEP samples, before any subsampling
# usage: ./rarefaction_curves_FC3_subsampled_103014ERD.R
# input: 	taxa tables at all levels
# output: 	pdfs of the rarefaction curves
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
input.path <- c("../data/FC3/summary_files/")	# input path
out.path <- c("../results/2_general_sub/")	# output path
#############################



##### Load libraries:
library(vegan)



##### Plot rarefaction curves:
for (a in c("phylum", "class", "order", "family", "genus")) {
	taxa <- read.table(file=paste0(input.path, "DEP.FC3.sub.",a,".counts.102914ERD.txt"), sep="\t", header=TRUE, stringsAsFactors=FALSE)
	
	# Add rownames:
	rownames(taxa) <- taxa$Fam
	taxa <- taxa[,-1]
	
	# Plot rarefaction curve:
	pdf(paste0(out.path, "plot_rarefaction_curve_",a,"_level_",today,"ERD.pdf"))
	rarecurve(t(taxa), step=10000, xlab="reads", ylab="taxa", main=paste0("Rarefaction curve:\n", a, " level (subsampled)"), label=FALSE, col="gray")
	dev.off()
}
	
print("DONE!")
	