#!/usr/bin/env Rscript

###### 
# This script will generate rarefaction curves for FC3 DEP samples, before any subsampling
# usage: ./rarefaction_curves_FC3_all_reads_102914ERD.R
# input: 	taxa tables at all levels
# output: 	pdfs of the rarefaction curves
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
input.path <- c("../data/FC3/summary_files/")	# input path
out.path <- c("../results/1_general/")	# output path
#############################



##### Load libraries:
library(vegan)



##### Load data and figure out who to exclude:
a <- "phylum"
taxa <- read.table(file=paste0(input.path, "DEP.FC3.",a,".counts.091514ERD.txt"), sep="\t", header=TRUE, stringsAsFactors=FALSE)

# Remove Hutterites:
taxa <- taxa[,-grep("HUTT", colnames(taxa))]
rownames(taxa) <- taxa$Fam
taxa <- taxa[,-1]

# What samples have fewer than 100k reads?:
mysums <- colSums(taxa)
torm <- names(which(mysums < 100000))
print("remove the following samples:")
print(torm)

for (a in c("phylum", "class", "order", "family", "genus")) {
	taxa <- read.table(file=paste0(input.path, "DEP.FC3.",a,".counts.091514ERD.txt"), sep="\t", header=TRUE, stringsAsFactors=FALSE)
	
	# Remove Hutterites:
	taxa <- taxa[,-grep("HUTT", colnames(taxa))]
	rownames(taxa) <- taxa$Fam
	taxa <- taxa[,-1]
	
	# Remove two samples worth removing:
	taxa <- taxa[,!colnames(taxa) %in% torm]
	
	# Plot rarefaction curve:
	pdf(paste0(out.path, "plot_rarefaction_curve_",a,"_level_",today,"ERD.pdf"))
	rarecurve(t(taxa), step=10000, xlab="reads", ylab="taxa", main=paste0("Rarefaction curve: ", a, " level"), label=FALSE, col="gray")
	abline(v=500000, col="red")
	dev.off()
}
	
print("DONE!")
	